from enum import Enum
from dataclasses import dataclass
from decimal import Decimal
from datetime import datetime
from typing import Optional

from trading_system.shared_kernel.value_objects.symbol import Symbol


class SignalType(Enum):
    """Types of trading signals"""
    BUY = "BUY"      # Open or increase position
    SELL = "SELL"    # Close or reduce position  
    HOLD = "HOLD"    # No action

    def is_actionable(self) -> bool:
        """Check if signal requires action"""
        return self != SignalType.HOLD
    
class SignalStrength(Enum):
    """Strength/confidence of signal"""
    WEAK = 1       # Low confidence
    MODERATE = 2   # Medium confidence
    STRONG = 3     # High confidence
    
    def to_position_multiplier(self) -> float:
        """Convert strength to position size multiplier"""
        # Weak=0.5x, Moderate=1x, Strong=1.5x base size
        return 0.5 + (self.value - 1) * 0.5
    

@dataclass(frozen=True)
class TradingSignal:
    """
    Represents a trading signal generated by a strategy.
    
    This is an immutable value object that captures the decision
    made by a trading algorithm at a specific point in time.
    """

    symbol: Symbol
    signal_type: SignalType
    strength: SignalStrength
    timestamp: datetime
    strategy_name: str

    # Optional metadata
    price: Optional[Decimal] = None
    indicators: Optional[dict] = None  # Store indicator values
    reason: Optional[str] = None       # Human-readable explanation

    def __post_init__(self):
        """ Validate signal data """
        if not self.symbol:
            raise ValueError("Signal must have a symbol")
        if not self.strategy_name:
            raise ValueError("Signal must have a strategy name")
        
    def to_dict(self) -> dict:
        """ Convert to dictionary for serialization """
        return {
            "symbol": str(self.symbol),
            "signal_type": self.signal_type.value,
            "strength": self.strength.value,
            "timestamp": self.timestamp.isoformat(),
            "strategy_name": self.strategy_name,
            "price": str(self.price) if self.price else None,
            "indicators": self.indicators,
            "reason": self.reason
        }




    
